name: Automatic Hosting
on:
  push:
    branches:
      - Nelson
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Frontend Dependencies
        run: |
          cd Frontend
          npm install

      - name: Build Frontend
        run: |
          cd Frontend
          npm run build

      - name: List build directory
        run: |
          ls -la Frontend/dist/cliente-app/browser

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: Frontend/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project ecommerce
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

          
