name: CI/CD Pipeline

on:
  push:
    branches:
      - Nelson  
  pull_request:
    branches:
      - Nelson

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build Backend
        working-directory: ./jwt
        run: mvn clean install

      - name: Test Backend
        working-directory: ./jwt
        run: mvn test

  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

      - name: Test Frontend
        working-directory: ./Frontend
        run: npm run test

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend
        working-directory: ./jwt
        run: |
          # Aquí puedes ejecutar comandos de despliegue para tu backend
          echo "Desplegando el backend..."

      - name: Deploy Frontend
        working-directory: ./Frontend
        run: |
          # Aquí puedes ejecutar comandos de despliegue para tu frontend
          echo "Desplegando el frontend..."
